### ISSUE TITLE
No contrast for link on "All conflicts resolved" merge conflict popover.

### ISSUE THREAD

**Issue by m-aciek** [mturlo/intellij-spacegray#1]
There is a light blue link (and a light gray description) on light blue background in popover at the end on solving merge conflicts.

<img width="1912" alt="Zrzut ekranu 2019-04-3 o 10 28 49" src="https://user-images.githubusercontent.com/9288014/55464581-b8609380-55fb-11e9-81c0-ab20ccc8b1c2.png">

**Comment by mturlo** [comment]
The light gray description should be dark, as in other places - I don't know, why it's not picking up that setting. Links are all light blue, so that's a problem.

How about if the informative tool window had its colours reversed, like so:
![image](https://user-images.githubusercontent.com/2657242/55491897-96d0cd80-5636-11e9-871b-b3e3fcf5e6d2.png)?

**Comment by m-aciek** [comment]
Looks very good to me :+1:.

**Comment by mturlo** [comment]
Version 1.1 submitted to JetBrains for review.
