### ISSUE TITLE
1.4.0 Code Hint Option Background

### ISSUE THREAD

**Issue by jjanusch** [mturlo/intellij-spacegray#9]
I noticed after the 1.4.0 update, the background for non-selected rows when using the autocomplete is a gray color rather than the usual blue.

![Screen Shot 2019-07-26 at 10 16 43 AM](https://user-images.githubusercontent.com/3516836/61969612-d2015e80-af8f-11e9-96e8-fe446bcaf565.png)

I noticed that [Gradianto](https://plugins.jetbrains.com/plugin/12334-gradianto) does not have this issue:

![Screen Shot 2019-07-26 at 10 27 37 AM](https://user-images.githubusercontent.com/3516836/61969712-07a64780-af90-11e9-834c-01407328a0b0.png)

But after resetting to Spacegray, it retained the purple from Gradianto until a restart:

![Screen Shot 2019-07-26 at 10 28 53 AM](https://user-images.githubusercontent.com/3516836/61969787-2efd1480-af90-11e9-9d1d-e1fa8a5d3b51.png)

So I am assuming this is a case of this theme not setting a specific color and the default being used.

**Comment by mturlo** [comment]
Ah, thanks for that! I've seen it happen since 2019.2 EAP and tried to fix it, but no dice. Then I've looked at other themes and seen the same happening (even the "official" ones like DarkPurple), so I thought it's a bug in 2019.2 and will get fixed eventually on the IDE level. But now it turns out there _is_ a way to fix it - I'll have to see what Gradianto does to overcome this.
